name = "EchoTale"
grammar = "echotale"
path_suffixes = ["etale"]
line_comments = ["# ", "// "]
block_comment = ["/*", "*/"]

[[brackets]]
start = "{"
end = "}"
close = true
newline = true

[[brackets]]
start = "<"
end = ">"
close = true
newline = false
